# Use a base image with the specified platform
FROM --platform=linux/amd64 ubuntu:latest

# Update apt sources and install required tools
# RUN apt update && \
#     apt install -y \
#     net-tools \
#     iproute2 \
#     iputils-ping \
#     curl \
#     vim \
#     openssl \
#     make \
#     git && \
#     # Clean up apt cache
#     apt clean

# # ENV GO111MODULE=on


# Set default working directory
WORKDIR /root

# Entry point (modifiable as needed)
# CMD ["/bin/bash"]