apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: debian-ssh-12-6
  namespace: devbox-system
spec:
  classRef: debian-ssh
  config:
    image: ghcr.io/cbluebird/devbox/debian-ssh-12.6:522dee
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    user: sealos
    workingDir: /home/sealos/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/sealos/project/entrypoint.sh
  description: debian-ssh 12.6
  version: "12.6"
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: debian-ssh
spec:
  title: "debian"
  kind: OS
  description: debian-ssh
