name: Build Docker Images

on:
  push:
    branches:
      - 'main'
    paths:
      - '**/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Get changed files
      id: getfile
      run: |
        chmod +x script/get_changed_files.sh
        script/get_changed_files.sh ${{ github.event.before }} ${{ github.sha }}
      shell: bash

    - name: Echo output
      run: |
        echo "Changed files: ${{ env.DIFF_OUTPUT }}"
        echo "Parent directories: ${{ env.PARENT_DIRS }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}

    - name: Build and push Docker image
      run: |
        TAG=${COMMIT_ID::6}
        chmod +x script/build_and_push_images.sh
        script/build_and_push_images.sh $TAG
      env:
        DOCKER_USERNAME: ${{ secrets.USERNAME }}
        COMMIT_ID: ${{ github.sha }}
      shell: bash

    - uses: actions/checkout@v3
    - name: generate runtime yaml
      run: |
        TAG=${COMMIT_ID::6}
        chmod +x script/generate_runtime_yaml.sh
        script/generate_runtime_yaml.sh $TAG
    - name: Commit runtime yaml
      run: |
        git config --global user.email "crk2778355976@163.com"
        git config --global user.name "cbluebird"
        git add yaml/
        git commit -m "generate runtime yaml"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}